config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'signup', to: 'users#new'
  post 'users', to: 'users#create'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last 20 }

end

app/models/user.rb
class User < ApplicationRecord

  before_save do
    self.username = username.downcase
  end

  validates :username,
            presence: true,
            length: {
              minimum: 3,
              maximum: 15
            },
            uniqueness: {
              case_sensitive: false
            }

  has_secure_password

  has_many :messages

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user,
                :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end

  def redirect_if_logged_in
    redirect_to root_path if logged_in?
  end

  def redirect_if_not_logged_in
    redirect_to login_path unless logged_in?
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

  before_action :redirect_if_not_logged_in, only: %i[index]

  def index
    @message = Message.new
    @messages = Message.custom_display
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :require_user

  def index
    @messages = Message.all
  end

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast 'chatroom_channel', mod_message: render_message(message)
      # redirect_to root_path
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def render_message(message)
    render(partial: 'message', locals: { message: message })
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :redirect_if_logged_in, only: %i[new]


  def new; end

  def create
    username = params[:session][:username].downcase
    password = params[:session][:password]
    user = User.find_by(username: username)
    if user && user.authenticate(password)
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to root_path
    else
      flash.now[:alert] = 'There was something wrong, we can\'t find your account!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out successfully'
    redirect_to login_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_if_logged_in, only: %i[new]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'You have successfully signed in'
      redirect_to root_path
    else
      flash[:alert] = @user.errors.full_messages
      redirect_to signup_path
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def check_flash(name)
    case name
    when 'alert'
      'warning'
    when 'info'
      'info'
    when 'success'
      'positive'
    else
      'info'
    end
  end

end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned icon header text-white">
  <i class="circular red coffee icon"></i>
  Say Something...
</h4>


<div class="ui two column grid">

  <div class="twelve wide column">

    <div class="ui card fluid raised chatbox">
      <div class="content messagesContainer">
        <div class="ui feed messageContainer" id='messageContainer'>
          <%= render @messages %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: { class: 'ui reply form', role: 'form' }, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input">
              <%= f.text_field :body, placeholder: 'Write a Message ...', type: 'text' %>
              <%= f.button '<i class="bordered inverted red paper plane outline icon"></i>'.html_safe,
                           class: 'button submit custom' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui card fluid raised chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_navigation.html.erb
<div class="ui fixed-top" style="padding: 20px">
  <div class="ui small inverted menu">
    <a href='<%= root_path %>' class="item red active">
      MessageME!
    </a>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="item">
        <% if logged_in? %>
          <div class="ui inverted black" style="margin-right: 20px; color: white"><%= current_user.username %></div>
          <%= link_to "Logout", logout_path, method: :delete, class: 'ui inverted black button' %>
        <% else %>
          <a href='<%= login_path %>' class="ui inverted black button" style="margin-right: 5px">Login</a>
          <a href="<%= signup_path %>" class="ui inverted black button">Sign Up</a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageMe</title>
  <%= favicon_link_tag %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body>
<div class="ui container">

  <% flash.each do |name, msg| %>
    <div class="ui <%= check_flash name %> message">
      <i class="close icon"></i>
      <%= msg %>
    </div>
  <% end %>


  <%= render 'layouts/navigation' %>
  <%= yield %>
</div>
</body>
</html>

app/views/messages/_message.html.erb
<%# @messages.each do |msg| %>
  <div class="event">
    <div class="content">
      <div class="summary">
        <%= message.user.username %>: <em><%= message.body %></em>
      </div>
    </div>
  </div>
<%# end %>

app/views/users/new.html.erb
<h4 class="ui center aligned icon header text-white">
  <i class="circular red coffee icon"></i>
  Create a new account
</h4>


<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">


      <%= form_with(model: @user, local: true, class: 'ui form') do |f| %>

        <div class="field">
          <%= f.label :username %>
          <div class="ui left icon input">
            <%= f.text_field :username, placeholder: 'Type your Username', type: 'text', required: true %>
            <i class="user icon"></i>
          </div>
        </div>

        <div class="field">
          <%= f.label :password %>
          <div class="ui left icon input">
            <%= f.text_field :password, placeholder: 'Type your Username', type: 'password', required: true %>
            <i class="user icon"></i>
          </div>
        </div>

        <div class="field">
          <div class="ui left icon width-100">
            <%= f.submit("Signup", class: 'ui blue submit button red left width-100') %>
          </div>
        </div>


      <% end %>


    </div>
    <div class="middle aligned column">
      <a href="<%= login_path %>" class="ui big button red">
        <i class="signup icon text-white"></i>
        Login
      </a>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>